### ISSUE TITLE
Bug: The app crashed when i click on update log on the about page.

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#28]
**Describe the bug**
When I clicked on the main menu icon and clicked on the about page to see option/information about the app. I clicked on the update log and the app crashed.

**To Reproduce**

1. Click on the menu at the top left side 
2. Click about
3. Then click on update log

**Expected behavior**
I expect that the app shouldn't crash. There should be info to see in the log 

**Screenshots**
https://youtu.be/V1UAiQB_Gfg

**Smartphone (please complete the following information):**
 - Device: [itel]
 - OS: [6.1]
 - Version 2.6.3.1(20190526)

###Log
```05-26 12:46:22.062 22516 23076 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
05-26 12:46:22.062 22516 23076 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 22516
05-26 12:46:22.062 22516 23076 E AndroidRuntime: java.lang.NoSuchFieldError: No static field Companion of type Lokio/ByteString$Companion; in class Lokio/ByteString; or its superclasses (declaration of 'okio.ByteString' appears in /data/app/top.geek_studio.chenlongcould.musicplayer.Common-1/base.apk)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http2.Http2.<clinit>(SourceFile:2)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Writer.connectionPreface(SourceFile:5)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Connection.start(SourceFile:2)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Connection.start(SourceFile:1)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.startHttp2(SourceFile:7)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:12)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(SourceFile:15)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(SourceFile:37)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:1)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.find(SourceFile:6)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.Transmitter.newExchange$okhttp(SourceFile:5)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:5)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:14)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:22)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:14)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:22)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:14)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:6)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:14)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:14)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(SourceFile:2)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(SourceFile:3)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-26 12:46:22.062 22516 23076 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)```

**Comment by AugustToko** [comment]
Emm. . What is the bug? Can you describe it in detail?🤔

**Comment by darewealth** [comment]
I have included the details.

**Comment by AugustToko** [comment]
> I have included the details.

Also due to okhttp, the intranet related operations have become abnormal. I will fix it tomorrow.

**Comment by AugustToko** [comment]
Has been fixed, you can view it on the release page

**Comment by darewealth** [comment]
It working perfectly. :+1
