### ISSUE TITLE
Bug: App crashed when i click force use net-album.

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#29]
**Describe the bug**
When I tried to use the force use net-album on the album page the app crashed.

**To Reproduce**

1. Click on the Album  
2. Click any music in any album
3. Click the 3 dots on the top right of the screen 
4. Then, click on Force use net-album
5. See error

**Expected behavior**
I don't really know the purpose of the function in the app, but according to what I think. it should help refresh the album. if that is not the purpose, I don't expect the app to crash.  

**Screenshots**
https://youtu.be/Uj8Bm0DpLZ0

**Smartphone (please complete the following information):**
 - Device: [itel]
 - OS: [6.1]
 - Version 2.6.3.1(20190526)

### Log
````05-26 12:47:10.105 23240 23240 E AndroidRuntime: FATAL EXCEPTION: main
05-26 12:47:10.105 23240 23240 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 23240
05-26 12:47:10.105 23240 23240 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:308)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.AlbumDetailActivity.b(SourceFile:4)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at i.a.a.b.a.q.onMenuItemClick(lambda)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(SourceFile:2)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(SourceFile:2)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at b.c.f.a.k.a(SourceFile:32)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at b.c.f.a.k.a(SourceFile:67)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at b.c.f.a.q.onItemClick(SourceFile:6)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3050)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:3905)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3670)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at androidx.appcompat.widget.DropDownListView.onTouchEvent(SourceFile:5)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(SourceFile:1)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9307)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2242)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2583)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1968)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9533)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-26 12:47:10.105 23240 23240 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by AugustToko** [comment]
Due to the okhttp library upgrade, the forced use of the network album map has crashed. I will fix it tomorrow.

**Comment by AugustToko** [comment]
Has been fixed, you can view it on the release page

**Comment by darewealth** [comment]
It working perfectly :+1:
