### ISSUE TITLE
Crash when click random play on detail

### ISSUE THREAD

**Issue by muhammadarif1** [AugustToko/ACG-Player#35]
**Describe the bug**
App crash when try to play random music using "random to play option"

**To Reproduce**
1. Open the app
2. Click on any music to play
3. Scroll down to black page and click dot 3 in beside of music title
4. Click show detail than chose "random to paly"
5. See error

**Expected behavior**
users should be able to play music randomly after one music ends using "random to play" option

**bug recording**
https://youtu.be/3kgfPlXX-n0

**Desktop (please complete the following information):**
 - OS: [ android 6.0]
 - Version[2.6.3.6]

**Smartphone (please complete the following information):**
 - Device: [oppo neo 7]
 - OS: 6.1

**Additional context**
```FATAL EXCEPTION: main
Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 768
java.lang.AssertionError: impossible
	at java.lang.Enum$1.create(Enum.java:45)
	at java.lang.Enum$1.create(Enum.java:35)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
	at java.lang.Enum.getSharedConstants(Enum.java:211)
	at java.lang.Enum.valueOf(Enum.java:191)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1602)
	at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:767)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
	at android.os.Parcel.readSerializable(Parcel.java:2378)
	at android.os.Parcel.readValue(Parcel.java:2203)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.BaseBundle.getSerializable(BaseBundle.java:988)
	at android.os.Bundle.getSerializable(Bundle.java:845)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onRestoreInstanceState(SourceFile:3)
	at android.view.View.dispatchRestoreInstanceState(View.java:13949)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3025)
	at android.view.View.restoreHierarchyState(View.java:13927)
	at b.o.a.w.a(SourceFile:192)
	at b.o.a.w.j(SourceFile:9)
	at b.o.a.w.n(SourceFile:7)
	at b.o.a.w.kc(SourceFile:2)
	at b.o.a.w.dispatchActivityCreated(SourceFile:3)
	at b.o.a.j.onStart(SourceFile:6)
	at b.c.a.n.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
	at android.app.Activity.performStart(Activity.java:6151)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
	at android.app.ActivityThread.access$800(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: java.lang.NoSuchMethodException: values []
	at java.lang.Class.getMethod(Class.java:664)
	at java.lang.Class.getDeclaredMethod(Class.java:626)
	at java.lang.Enum$1.create(Enum.java:41)
	... 38 more```

**Comment by AugustToko** [comment]
Fixed, posted to release page later

**Comment by AugustToko** [comment]
already updated
