### ISSUE TITLE
clicking on ARTIST, and scrolling makes the app to crash

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#37]
**Describe the bug**
Each time i click on `ARTIST`, some of the song in the list disappears, and if i tried to scroll, the app crashes

**To Reproduce**
- Launch the app
- click on `ARTIST`, You will notice some abnormalities. I.e, some songs will disappear
- scroll up or down and note the crash

**Expected behavior**
I expected the songs under `ARTIST` to be listed and intact and also be able to scroll without the app crashing.

**Screenshots**
https://youtu.be/3oHaXgjv5Fc

**Smartphone 
 - Device: [Tecno spark k7]
 - OS: [Android 7.0]
 - App version [2.6.3.6]

**Additional context**
It was working fine in the previous version, but threw an error in this updated one.

### Logcat

``` FATAL EXCEPTION: main
05-24 21:45:57.991  7125  7125 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 7125
05-24 21:45:57.991  7125  7125 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{top.geek_studio.chenlongcould.musicplayer.Common/top.geek_studio.chenlongcould.musicplayer.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'h.a.a.b.b.Ea h.a.a.b.d.kb.getAdapter()' on a null object reference
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6251)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'h.a.a.b.b.Ea h.a.a.b.d.kb.getAdapter()' on a null object reference
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.W(SourceFile:6)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.a(SourceFile:2)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at h.a.a.b.a.yb.onQueryTextChange(SourceFile:1)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at com.miguelcatalan.materialsearchview.MaterialSearchView.onTextChanged(SourceFile:9)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at com.miguelcatalan.materialsearchview.MaterialSearchView.c(SourceFile:2)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at c.e.a.b.onTextChanged(SourceFile:3)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.TextView.sendOnTextChanged(TextView.java:8526)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.TextView.setText(TextView.java:4526)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.TextView.setText(TextView.java:4380)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.EditText.setText(EditText.java:95)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.TextView.setText(TextView.java:4355)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.widget.TextView.onRestoreInstanceState(TextView.java:4246)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.View.dispatchRestoreInstanceState(View.java:16399)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3438)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.view.View.restoreHierarchyState(View.java:16377)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2161)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.Activity.onRestoreInstanceState(Activity.java:1053)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.Activity.performRestoreInstanceState(Activity.java:1008)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1174)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
05-24 21:45:57.991  7125  7125 E AndroidRuntime: ... 9 more```

**Comment by AugustToko** [comment]
Ok, I will fix it recently.

**Comment by AugustToko** [comment]
try new version

**Comment by cckole** [comment]
Weldone @AugustToko. Yes the app is no more crashing , but while using it, it hanged in playlist and I had to click on the phone back button to bring it back to life. I've experienced it twice. I would have shown you the video but it happens when you don't expect. Moreso, scrolling in the `Artist` is not as slik as scrolling in other parts. You can look into that as well. Thank you for your swift response and the hard work you are doing on your project. I believe it will be bug free with your persistent releases. Thumbs up.

**Comment by AugustToko** [comment]
> Weldone @AugustToko. Yes the app is no more crashing , but while using it, it hanged in playlist and I had to click on the phone back button to bring it back to life. I've experienced it twice. I would have shown you the video but it happens when you don't expect. Moreso, scrolling in the `Artist` is not as slik as scrolling in other parts and also, the icon of every song turns white as I scroll. You can look into that as well. Thank you for your swift response and the hard work you are doing on your project. I believe it will be bug free with your persistent releases. Thumbs up.

Thank you very much for your encouragement.
The artist picture turned white because I used a website to get the artist image, but it now always returns the same image. I guess there is a problem with that website, I will replace the data source as soon as possible.
