### ISSUE TITLE
Bug: App crashed when i click on shuffle icon  in the trash can.

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#38]
**Describe the bug**
When I clicked on the shuffle icon in the trash can the app crashed 

**To Reproduce**

1. Click on the playlist 
2. Go to trash can
3. Then, click on the shuffle icon by the right at the top 
5. See error

**Expected behavior**
 I expect to get a popup message that there is not music to shuffle, or it shouldn't have a negative effect.   

**Screenshots**
https://youtu.be/R7kzi31FUxA

**Smartphone 
 - Device: [Gionee X1]
 - OS: [7.0]
 - Version 2.6.3.5(20190527)

### Log
```05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: FATAL EXCEPTION: main
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 31617
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {top.geek_studio.chenlongcould.musicplayer.Common/top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity}: java.lang.NullPointerException: Attempt to read from field 'int i.a.a.b.h.f.Uvc' on a null object reference
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4410)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4428)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'int i.a.a.b.h.f.Uvc' on a null object reference
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.onDestroy(SourceFile:12)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7232)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
05-29 14:44:46.344 10086 31617 31617 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4397)```

**Comment by AugustToko** [comment]
fixed ,will upload to release page

**Comment by darewealth** [comment]
The feature now works perfectly, I am happy you worked on it. And I must commend the good work you are doing. more power to your elbow.

**Comment by darewealth** [comment]
Hello friend, I think it would be better if you close any issue you had fixed. Just like this one.

**Comment by AugustToko** [comment]
> Hello friend, I think it would be better if you close any issue you had fixed. Just like this one.

I think too, I am under a lot of pressure on these issues.) Hahaha
