### ISSUE TITLE
ACG-Player v2.6.5.3(20190530); The app crashes anytime I try to access the app from the notifcation panel. 

### ISSUE THREAD

**Issue by HarryHeights** [AugustToko/ACG-Player#42]
**Describe the bug**
When I launched the app and played a song, the music controls of the app on my notification panel appeared. That's expected. Naturally, it would be possible for me to access the music player by clicking on the music player's notification. When I did that, the app crashed. 

**To Reproduce**

1. Play a song
2. Access the music controls on your notification panel (You could be on the app or on another app).
3. Tap on the notification panel

**Expected behavior**
The expectation for the action I tried out is very straightforward. As is with other music player or apps, clicking on the notification should open the app. 

**Screen recording**
https://youtu.be/Uiyh33Gvnl0

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1.0
 - Software version: v2.6.5.3(20190530)

**Logcat**
``` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
	at top.geek_studio.chenlongcould.musicplayer.broadcast.ReceiverOnMusicPlay.playFromUri(SourceFile:2)
	at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.receivedIntentCheck(SourceFile:6)
	at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.onNewIntent(SourceFile:2)
	at android.app.Activity.performNewIntent(Activity.java:7096)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1310)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1322)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2968)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2984)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3000)
	at android.app.ActivityThread.-wrap14(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1693)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by AugustToko** [comment]
Ok, I also found this bug, I will fix it today.

**Comment by HarryHeights** [comment]
Alright cool.

**Comment by AugustToko** [comment]
fixed, will upload to release page

**Comment by HarryHeights** [comment]
I really love your responsiveness to issues. One of the most active dev I've seen on Github

**Comment by AugustToko** [comment]
> I really love your responsiveness to issues. One of the most active dev I've seen on Github

Hahaha, great honor
