### ISSUE TITLE
ACG-Player v2.6.5.3(20190530); The app crashes if I try to add the same song to a playlist. 

### ISSUE THREAD

**Issue by HarryHeights** [AugustToko/ACG-Player#43]
**Describe the bug**
I created a playlist and added a song to it. Whilst still checking out the playlist feature, I tried to add the same song to the same playlist. The app crashed when I tried that. 

**To Reproduce**
1. To create a playlist, you have to use a song on the list. 
2. Click on the 3 dots beside any track/song
3. Click on 'add playlist' option
4. Create a playlist
5. Try to add the same song to the same playlist
6. See error. 

**Expected behavior**
There are two possible outcomes/behaviours that I expected. 
- I expected that the app would notify me that the song already exists on the playlist. Or,
- The song is also added to the playlist as a duplicate(this would rarely happen though). But it's not impossible. 

**Screen recording**
https://youtu.be/d06FV7uJAQw

**Test Environment:**
- Device: RedMi Note 5 Pro
- OS: Android 8.1.0
- Software version;  ACG-Player v2.6.5.3(20190530)

**Logcat**

``` java.lang.NullPointerException: Attempt to invoke virtual method 'int top.geek_studio.chenlongcould.musicplayer.model.PlayListItem.getId()' on a null object reference
	at top.geek_studio.chenlongcould.musicplayer.utils.Utils$DataSet.a(SourceFile:22)
	at i.a.a.b.g.k.onClick(Unknown Source:4)
	at b.c.a.k.onItemClick(SourceFile:1)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3165)
	at android.widget.AbsListView$3.run(AbsListView.java:4147)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

```

**Comment by AugustToko** [comment]
Try the new version (release page), it may have been fixed

**Comment by HarryHeights** [comment]
Oh okay. I'll

**Comment by HarryHeights** [comment]
Issue has been fixed
