### ISSUE TITLE
Music stop when i minimize the app

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#44]
**Describe the bug**
When I play music on the app and I want to listen to it while doing other things then when I minimize the app the music I was playing stopped.

**To Reproduce**

1. Launch the app
2. Play any music 
3. Minimize the app

**Expected behavior**
I expect the music continue to play underneath, and it shows as well show on the top notification bar that music is currently playing.

**Screenshots**
https://youtu.be/SlqY8jEkRi0

**Smartphone.
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.5.3(20190531)]
### Log
```05-31 07:47:57.940 23665 23665 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 23665
05-31 07:47:57.940 23665 23665 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.broadcast.ReceiverOnMusicPlay.playFromUri(SourceFile:2)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.receivedIntentCheck(SourceFile:6)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.MainActivity.onNewIntent(SourceFile:2)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1215)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1227)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2546)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2558)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2567)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-31 07:47:57.940 23665 23665 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by darewealth** [comment]
The issue still persist in the  latest  version

**Comment by AugustToko** [comment]
try new version

**Comment by darewealth** [comment]
It works good job :+1:
