### ISSUE TITLE
App crashed when I exit.

### ISSUE THREAD

**Issue by cckole** [AugustToko/ACG-Player#50]
**Describe the bug**
While playing a song, I clicked on the three dots at the top by the left to exit the app, and immediately I clicked on `Exit`, the app crashed and the music i was listening to stopped.

**To Reproduce**
1. Launch the app
2. play any song
3. click on the three dots at the top by the left side
4. Click on `exit`
5. See the crash

**Expected behavior**

I expected the app to close and the song to keep playing when I clicked on `exit` 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Tecno spark k7]
 - OS: [Android 7.0]
 - Version [2.6.5.8]
https://github.com/AugustToko/ACG-Player/issues/50

### Logcat

```FATAL EXCEPTION: main
06-02 10:42:16.616 23206 23206 E AndroidRuntime: Process: com.teocci.ytinbg, PID: 23206
06-02 10:42:16.616 23206 23206 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.teocci.ytinbg.adapters.VideosAdapter.clearYouTubeVideos()' on a null object reference
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.teocci.ytinbg.ui.fragments.SearchFragment.searchQuery(SearchFragment.java:190)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.teocci.ytinbg.ui.MainActivity.handleIntent(MainActivity.java:488)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.teocci.ytinbg.ui.MainActivity.access$300(MainActivity.java:69)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.teocci.ytinbg.ui.MainActivity$3.onSuggestionClick(MainActivity.java:360)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.support.v7.widget.SearchView.onItemClicked(SearchView.java:1387)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.support.v7.widget.SearchView$8.onItemClick(SearchView.java:1413)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1029)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AutoCompleteTextView.-wrap1(AutoCompleteTextView.java)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1326)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AdapterView.performItemClick(AdapterView.java:315)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AbsListView.performItemClick(AbsListView.java:1204)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AbsListView$PerformClick.run(AbsListView.java:3321)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.widget.AbsListView$4.run(AbsListView.java:4382)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6251)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
06-02 10:42:16.616 23206 23206 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)```

**Comment by AugustToko** [comment]
"exit" is the function I used to completely quit the app.
You can just press the back button of the navigation bar instead of clicking exit

**Comment by cckole** [comment]
That is another good way. However, you can make it not to crash if the exit is clicked. Thanks for the response.

**Comment by AugustToko** [comment]
Ok, I have already located the cause of the crash, the next version is coming soon

**Comment by cckole** [comment]
Alright, that's good. Thanks.

**Comment by AugustToko** [comment]
fixed

**Comment by cckole** [comment]
Tested and working fine. No more crashing. Thanks.
