### ISSUE TITLE
Bug: App crashed when I tried to go-back from the trash can

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#51]
**Describe the bug**

When I access the playlist and clicked on the Trash can, the app crashed when I tried to go back with both the app back button and the mobile back button.

**To Reproduce**

1. Launch the app
2. Click on Playlist
3. Then click on the Trash can 
4. And click on the app or phone back button 

**Expected behavior**

I expect to use the back button without any issue. 

**Screenshots**
https://youtu.be/LJh3f63BRAg

**Smartphone 
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.5.8]
### Log
``` FATAL EXCEPTION: main
06-02 11:32:03.934 22980 22980 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common:musicService, PID: 22980
06-02 11:32:03.934 22980 22980 E AndroidRuntime: java.lang.RuntimeException: Unable to start service top.geek_studio.chenlongcould.musicplayer.MusicService@e683846 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.MusicService.onStartCommand(SourceFile:1)
06-02 11:32:03.934 22980 22980 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3011)```

**Comment by AugustToko** [comment]
Emm This function is normal on my phone. If I want to locate your crash, I need a log file.
You can use adb tools to get the log for me.

**Comment by darewealth** [comment]
Done

**Comment by AugustToko** [comment]
try new version, may fixed

**Comment by darewealth** [comment]
It works perfectly :+1:
