### ISSUE TITLE
Bug: App crashed when I tried to go-back from the History(RAM)

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#52]
**Describe the bug**

When I access the playlist and clicked on the History(RAM), the app crashed when I tried to go back with both the app back button and the mobile back button.

**To Reproduce**

1. Launch the app
2. Click on Playlist
3. Then click on the History (RAM)
4. And click on the app or phone back button 

**Expected behavior**

I expect to use the back button without any issue. 

**Screenshots**
https://youtu.be/u_paW-UiiiU

**Smartphone 
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.5.8]

### Log
```
06-02 10:50:08.189  8943  8943 E AndroidRuntime: FATAL EXCEPTION: main
06-02 10:50:08.189  8943  8943 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 8943
06-02 10:50:08.189  8943  8943 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {top.geek_studio.chenlongcould.musicplayer.Common/top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void top.geek_studio.chenlongcould.musicplayer.IMuiscService.addToOrderList(top.geek_studio.chenlongcould.musicplayer.model.MusicItem)' on a null object reference
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3846)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3864)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void top.geek_studio.chenlongcould.musicplayer.IMuiscService.addToOrderList(top.geek_studio.chenlongcould.musicplayer.model.MusicItem)' on a null object reference
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.Data.syncPlayOrderList(SourceFile:5)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.onDestroy(SourceFile:7)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6476)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1145)
06-02 10:50:08.189  8943  8943 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3833)```

**Comment by AugustToko** [comment]
Emm This function is normal on my phone. If I want to locate your crash, I need a log file.
You can use adb tools to get the log for me.

**Comment by darewealth** [comment]
Done

**Comment by AugustToko** [comment]
try new version (release page)

**Comment by darewealth** [comment]
It works perfectly :+1:
