### ISSUE TITLE
App crashed when i clicked on favorites in playlist

### ISSUE THREAD

**Issue by darewealth** [AugustToko/ACG-Player#54]
**Describe the bug**

When I access the playlist and clicked on Favorites, the app crashed.

**To Reproduce**

1. Launch the app
2. Click on Playlist
3. Then click on the favorites
4. And see error 

**Expected behavior**

I expected to access the add recent successfully 

**Screenshots**
https://youtu.be/VdQsB9vgVrs

**Smartphone 
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.5.8]
### Log
```06-02 11:19:37.234 19277 19277 E AndroidRuntime: FATAL EXCEPTION: main
06-02 11:19:37.234 19277 19277 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 19277
06-02 11:19:37.234 19277 19277 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{top.geek_studio.chenlongcould.musicplayer.Common/top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void top.geek_studio.chenlongcould.musicplayer.IMuiscService.addToOrderList(top.geek_studio.chenlongcould.musicplayer.model.MusicItem)' on a null object reference
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void top.geek_studio.chenlongcould.musicplayer.IMuiscService.addToOrderList(top.geek_studio.chenlongcould.musicplayer.model.MusicItem)' on a null object reference
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.Data.syncPlayOrderList(SourceFile:5)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.activity.ListViewActivity.onCreate(SourceFile:48)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6305)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
06-02 11:19:37.234 19277 19277 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)```

**Comment by AugustToko** [comment]
Emm This function is normal on my phone. If I want to locate your crash, I need a log file.
You can use adb tools to get the log for me.

**Comment by darewealth** [comment]
I will put the log now

**Comment by AugustToko** [comment]
> I will put the log now

thanks

**Comment by darewealth** [comment]
Done

**Comment by AugustToko** [comment]
try new vresion

**Comment by darewealth** [comment]
It works perfectly now :+1:
