### ISSUE TITLE
ACG-Player v2.6.9.3: The app crashes when I use the shuffle button in the "history page".

### ISSUE THREAD

**Issue by HarryHeights** [AugustToko/ACG-Player#82]
**Describe the bug**
I experienced a fault while on the history page on the app. I launched the app, I didn't play any song. I was checking out all the music menus again. I accessed the history page and clicked on the shuffle button. The app crashed. This behaviour was also reproduced when I tried the same thing in the trashcan. 

**To Reproduce**

1. Launch app but don't play any song.
2. Swipe to playlist tab
3. Click on history
4. On the history page, click the shuffle button
5. See error.

**Expected behavior**
I expected that when I clicked the shuffle icon, the app will select and play any song at random. 
I honestly don't see the need for that button to be on that page. 

**Screen recording**
https://youtu.be/6xrwsrZB2fE

**Test environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 9.0
 - Software Version: ACG-Player v2.6.9.3

**Logcat**

``` java.lang.AssertionError: impossible
	at java.lang.Enum$1.create(Enum.java:272)
	at java.lang.Enum$1.create(Enum.java:262)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Enum.valueOf(Enum.java:244)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1745)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at android.os.Parcel.readSerializable(Parcel.java:2935)
	at android.os.Parcel.readValue(Parcel.java:2722)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3045)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
	at android.os.BaseBundle.getSerializable(BaseBundle.java:1236)
	at android.os.Bundle.getSerializable(Bundle.java:1034)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onRestoreInstanceState(SourceFile:3)
	at android.view.View.dispatchRestoreInstanceState(View.java:18635)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3823)
	at android.view.View.restoreHierarchyState(View.java:18613)
	at b.o.a.i.restoreViewState(SourceFile:2)
	at b.o.a.x.a(SourceFile:171)
	at b.o.a.x.i(SourceFile:9)
	at b.o.a.x.l(SourceFile:13)
	at b.o.a.x.Ob(SourceFile:2)
	at b.o.a.k.onStart(SourceFile:9)
	at b.c.a.n.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
	at android.app.Activity.performStart(Activity.java:7252)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NoSuchMethodException: values []
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at java.lang.Enum$1.create(Enum.java:268)
	... 39 more
```

**Comment by AugustToko** [comment]
It works fine on my device. Do you make a crash every time you click?

**Comment by HarryHeights** [comment]
Yea

**Comment by HarryHeights** [comment]
Did you follow my steps to reproduce the bug. 
- Exit the app.completely
- Launch it again and don't play any song
- Go to either the trashcan or history page on the playlist
- Click the shuffle icon.

**Comment by AugustToko** [comment]
try new version, I added the judgment of the empty elements of the list.

**Comment by HarryHeights** [comment]
The new version works perfectly
